exports.radiantStr = [
  ['Earthshaker', 'Sven', 'Tiny', 'Kunkka'],
  ['Beast Master', 'Dragon Knight', 'Clockwerk', 'Omniknight'],
  ['Huskar', 'Alchemist', 'Brewmaster', 'Treant Protector'],
  ['Io', 'Centaur Warrunner', 'Timbersaw', 'Bristleback'],
  ['Tusk', 'Elder Titan', 'Legion Commander', 'Earth Spirit'],
  ['Phoenix']
];

exports.direStr = [
  ['Axe', 'Pudge', 'Sand King', 'Slardar'],
  ['Tidehunter', 'Wraith King', 'Lifestealer', 'Night Stalker'],
  ['Doom', 'Spirit Breaker', 'Lycan', 'Chaos Knight'],
  ['Undying', 'Magnus', 'Abaddon']
];

exports.radiantAgi = [
  ['Anti-Mage', 'Drow Ranger', 'Juggernaut', 'Mirana'],
  ['Morphling', 'Phantom Lancer', 'Vengeful Spirit', 'Riki'],
  ['Sniper', 'Templar Assassin', 'Luna', 'Bounty Hunter'],
  ['Ursa', 'Gyrocopter', 'Lone Druid', 'Naga Siren'],
  ['Troll Warlord', 'Ember Spirit']
];

exports.direAgi = [
  ['Bloodseeker', 'Shadow Fiend', 'Razor', 'Venomancer'],
  ['Faceless Void', 'Phantom Assassin', 'Viper', 'Clinkz'],
  ['Broodmother', 'Weaver', 'Spectre', 'Meepo'],
  ['Nyx Assassin', 'Slark', 'Medusa', 'Terrorblade']
];

exports.radiantInt = [
  ['Crystal Maiden', 'Puck', 'Storm Spirit', 'Windranger'],
  ['Zeus', 'Lina', 'Shadow Shaman', 'Tinker'],
  ['Nature\'s Prophet', 'Enchantress', 'Jakiro', 'Chen'],
  ['Silencer', 'Ogre Magi', 'Rubick', 'Disruptor'],
  ['Keeper of the Light', 'Skywrath Mage', 'Oracle', 'Techies']
];

exports.direInt = [
  ['Bane', 'Lich', 'Lion', 'Witch Doctor'],
  ['Enigma', 'Necrophos', 'Warlock', 'Queen of Pain'],
  ['Death Prophet', 'Pugna', 'Dazzle', 'Leshrac'],
  ['Dark Seer', 'Batrider', 'Ancient Apparition', 'Invoker'],
  ['Outworld Devourer', 'Shadow Demon', 'Visage', 'Winter Wyvern']
];

exports.nameHash = {
  abbadon: 'Abbadon',
  alchemist: 'Alchemsist',
  ancientapparition: 'Ancient Apparition',
  antimage: 'Anti-Mage',
  axe: 'Axe',
  bane: 'Bane',
  batrider: 'Batrider',
  beastmaster: 'Beast Master',
  bloodseeker: 'Bloodseeker',
  bountyhunter: 'Bounty Hunter',
  brewmaster: 'Brewmaster',
  bristleback: 'Bristleback',
  broodmother: 'Broodmother',
  centaurwarrunner: 'Centaur Warrunner',
  chaosknight: 'Chaos Knight',
  chen: 'Chen',
  clinkz: 'Clinkz',
  clockwerk: 'Clockwerk',
  crystalmaiden: 'Crystal Maiden',
  darkseer: 'Dark Seer',
  dazzle: 'Dazzle',
  deathprophet: 'Death Prophet',
  disruptor: 'Disruptor',
  doom: 'Doom',
  dragonknight: 'Dragon Knight',
  drowranger: 'Draw Ranger',
  earthshaker: 'Earthshaker',
  earthspirit: 'Earth Spirit',
  eldertitan: 'Elder Titan',
  emberspirit: 'Ember Spirit',
  enchantress: 'Ehnchantress',
  enigma: 'Enigma',
  facelessvoid: 'Faceless Void',
  gyrocopter: 'Gyrocopter',
  huskar: 'Huskar',
  invoker: 'Invoker',
  jakiro: 'Jakiro',
  juggernaut: 'Juggernaut',
  keeperofthelight: 'Keeper of the Light',
  kunkka: 'Kunkka',
  legioncommander: 'Legion Commander',
  leshrac: 'Leshrac',
  lich: 'Lich',
  lifestealer: 'Lifestealer',
  lina: 'Lina',
  lion: 'Lion',
  lonedruid: 'Lone Druid',
  luna: 'Luna',
  lycan: 'Lycan',
  magnus: 'Magnus',
  medusa: 'Medusa',
  meepo: 'Meepo',
  mirana: 'Mirana',
  morphling: 'Morphling',
  nagasiren: 'Naga Siren',
  naturesprophet: 'Nature\'s Prophet',
  necrophos: 'Necrophos',
  nightstalker: 'Night Stalker',
  nyxassassin: 'Nyx Assassin',
  ogremagi: 'Ogre Magi',
  omniknight: 'Omniknight',
  oracle: 'Oracle',
  outworlddevourer: 'Outerworld Devourer',
  phantomassassin: 'Phantom Assassin',
  phantomlancer: 'Phantom Lancer',
  phoenix: 'Phoenix',
  puck: 'Puck',
  pudge: 'Pudge',
  pugna: 'Pugna',
  queenofpain: 'Queen of Pain',
  razor: 'Razor',
  riki: 'Riki',
  rubick: 'Rubick',
  sandking: 'Sand King',
  shadowdemon: 'Shadow Demon',
  shadowfiend: 'Shadowfiend',
  shadowshaman: 'Shadow Shaman',
  silencer: 'Silencer',
  wraithking: 'Wraith King',
  skywrathmage: 'Skywrath Mage',
  slardar: 'Slardar',
  slark: 'Slark',
  sniper: 'Sniper',
  spectre: 0,
  spiritbreaker: 0,
  stormspirit: 0,
  sven: 0,
  techies: 0,
  templarassassin: 0,
  terrorblade: 0,
  tidehunter: 0,
  timbersaw: 0,
  tinker: 0,
  tiny: 0,
  treantprotector: 0,
  trollwarlord: 0,
  tusk: 0,
  undying: 0,
  ursa: 0,
  vengefulspirit: 0,
  venomancer: 0,
  viper: 0,
  visage: 0,
  warlock: 0,
  weaver: 0,
  windrunner: 0,
  winterwyvern: 0,
  io: 0,
  witchdoctor: 0,
  zeus: 0
};