var heroController = require('../controllers/heroController.js');

var rikiCounters = {
  abbadon: 5,
  alchemist: 0,
  ancientapparition: 5,
  antimage: 5,
  axe: -3,
  bane: 5,
  batrider: 0,
  beastmaster: 0,
  bloodseeker: 0,
  bountyhunter: -3,
  brewmaster: 0,
  bristleback: 0,
  broodmother: -5,
  centaurwarrunner: -5,
  chaosknight: 0,
  chen: 0,
  clinkz: 0,
  clockwerk: 0,
  crystalmaiden: 0,
  darkseer: 0,
  dazzle: 0,
  deathprophet: 0,
  disruptor: 0,
  doom: -3,
  dragonknight: 0,
  drowranger: 0,
  earthshaker: 0,
  earthspirit: 0,
  eldertitan: 0,
  emberspirit: 0,
  enchantress: 0,
  enigma: 0,
  facelessvoid: 0,
  gyrocopter: 5,
  huskar: 5,
  invoker: 5,
  jakiro: 5,
  juggernaut: 5,
  keeperofthelight: 5,
  kunkka: 0,
  legioncommander: -5,
  leshrac: -3,
  lich: 0,
  lifestealer: 5,
  lina: 5,
  lion: -5,
  lonedruid: 0,
  luna: 0,
  lycan: 5,
  magnus: 5,
  medusa: 5,
  meepo: 0,
  mirana: 5,
  morphling: 5,
  nagasiren: -3,
  naturesprophet: 0,
  necrophos: 0,
  nightstalker: 0,
  nyxassassin: 5,
  ogremagi: -3,
  omniknight: 0,
  oracle: 0,
  outworlddevourer: -3,
  phantomassassin: -5,
  phantomlancer: 0,
  phoenix: 5,
  puck: 0,
  pudge: 5,
  pugna: 0,
  queenofpain: 0,
  razor: -5,
  riki: 0,
  rubick: 5,
  sandking: 0,
  shadowdemon: 5,
  shadowfiend: 0,
  shadowshaman: 0,
  silencer: -5,
  wraithking: 5,
  skywrathmage: -5,
  slardar: -5,
  slark: 5,
  sniper: 5,
  spectre: 0,
  spiritbreaker: 0,
  stormspirit: -3,
  sven: 0,
  techies: 0,
  templarassassin: 0,
  terrorblade: 0,
  tidehunter: 0,
  timbersaw: 0,
  tinker: 0,
  tiny: -5,
  treantprotector: 0,
  trollwarlord: -3,
  tusk: 0,
  undying: 5,
  ursa: 5,
  vengefulspirit: 0,
  venomancer: -3,
  viper: 5,
  visage: 0,
  warlock: 0,
  weaver: 5,
  windrunner: 0,
  winterwyvern: 0,
  io: 0,
  witchdoctor: 0,
  zeus: -3
}

var earthshakerCounters = {
  abbadon: 0,
  alchemist: -5,
  ancientapparition: -3,
  antimage: -5,
  axe: -5,
  bane: 5,
  batrider: 0,
  beastmaster: 0,
  bloodseeker: 0,
  bountyhunter: 0,
  brewmaster: 0,
  bristleback: 0,
  broodmother: 5,
  centaurwarrunner: 0,
  chaosknight: 5,
  chen: -3,
  clinkz: -5,
  clockwerk: -5,
  crystalmaiden: 5,
  darkseer: 5,
  dazzle: 0,
  deathprophet: -5,
  disruptor: -5,
  doom: -5,
  dragonknight: 0,
  drowranger: -5,
  earthshaker: 0,
  earthspirit: 0,
  eldertitan: 0,
  emberspirit: 0,
  enchantress: 0,
  enigma: 5,
  facelessvoid: 0,
  gyrocopter: 0,
  huskar: -5,
  invoker: -3,
  jakiro: 0,
  juggernaut: -5,
  keeperofthelight: -3,
  kunkka: 0,
  legioncommander: 5,
  leshrac: -3,
  lich: -3,
  lifestealer: -5,
  lina: 5,
  lion: -5,
  lonedruid: 0,
  luna: 0,
  lycan: 0,
  magnus: 5,
  medusa: 0,
  meepo: 0,
  mirana: 0,
  morphling: 0,
  nagasiren: 5,
  naturesprophet: 0,
  necrophos: 0,
  nightstalker: 0,
  nyxassassin: -5,
  ogremagi: 0,
  omniknight: 0,
  oracle: 0,
  outworlddevourer: 0,
  phantomassassin: 5,
  phantomlancer: 0,
  phoenix: -5,
  puck: 0,
  pudge: -3,
  pugna: 0,
  queenofpain: 0,
  razor: 0,
  riki: -5,
  rubick: -5,
  sandking: 5,
  shadowdemon: 0,
  shadowfiend: -3,
  shadowshaman: 0,
  silencer: -5,
  wraithking: -3,
  skywrathmage: 0,
  slardar: 5,
  slark: 5,
  sniper: -3,
  spectre: -5,
  spiritbreaker: -5,
  stormspirit: 0,
  sven: 0,
  techies: 0,
  templarassassin: -5,
  terrorblade: 5,
  tidehunter: 0,
  timbersaw: -5,
  tinker: 0,
  tiny: 0,
  treantprotector: 0,
  trollwarlord: 0,
  tusk: 5,
  undying: 5,
  ursa: 0,
  vengefulspirit: 5,
  venomancer: 0,
  viper: -5,
  visage: -3,
  warlock: 0,
  weaver: 0,
  windrunner: 0,
  winterwyvern: 0,
  io: 0,
  witchdoctor: 0,
  zeus: -5
}

var addStubs = function() {
  heroController.updateByName('riki', rikiCounters, function(err, res) {
    if (err) {
      console.log(err);
      return;
    }
    // console.log('Updated Riki');
  });

  heroController.updateByName('earthshaker', earthshakerCounters, function(err, res) {
    if (err) {
      console.log(err);
      return;
    }
    // console.log('Updated Earthshaker');
  });
}

module.exports = addStubs;

